### ISSUE TITLE
`Plugins/Wormhole` attach images instead of posting link

### ISSUE THREAD

**Issue by TretinV3** [Curiosity-org/Gipsy#102]
```
def array linkToAdd;
for link in message do
  if link is image and link is surround by "<>" then
    add link to linkToAdd;
  end
end
for every link in linkToAdd do
  add link to message.attachement;
end
```

**Comment by ZRunner** [comment]
Cannot repro: the plugin seems to correctly send attachments as files and not as links, see https://github.com/Curiosity-org/Gipsy/blob/88adb1b80032a5b3bd7e95fd82b7772bd5c2fd63/plugins/wormhole/wormhole.py#L49 and https://github.com/Curiosity-org/Gipsy/blob/88adb1b80032a5b3bd7e95fd82b7772bd5c2fd63/plugins/wormhole/wormhole.py#L72-L80

**Comment by ascpial** [comment]
L'idée serait plutôt, de ce que je comprends, de mettre les images mises sous forme de lien dans le message en attachment, probablement pour résoudre les GIFs tenor.
