### ISSUE TITLE
[help] wrong argument type for some commands

### ISSUE THREAD

**Issue by ascpial** [Curiosity-org/Gipsy#150]
Quelques commandes ne supportent pas le message d'aide comme par exemple la commande `wormhole link`.
Il faudrait modifier le comportement suivant pour que les valeurs soient correctement affichées :

![image](https://user-images.githubusercontent.com/72463129/221803150-c9503c60-4e96-4658-bc6d-602779aeb072.png)

Il faudra aussi vérifier qu'il n'y a pas de problèmes similaires dans d'autres commandes, ce qui est probablement le cas.

**Comment by ascpial** [comment]
Par exemple il faudra ajouter le support de l'aide pour la commande `!rolelink add`.

**Comment by ZRunner** [comment]
Si je comprend bien le ticket, le bug est que la valeur par défaut pour certaines commandes n'est pas correctement affichée, n'est-ce pas ?

Dans ce cas, seule la commande `wormhole link` est affectée, c'est la seule qui aie un paramètre prenant une valeur par défaut autre que None

**Comment by ascpial** [comment]
C'est cela, il faut afficher une valeur par défaut.
Il est possible que la manière de le gérer soit déjà implémenté et qu'il faille juste l'ajouter sur les bonnes classes, mais je ne suis plus certain, il faut regarder le code.

Je penses qu'il y a d'autres commandes affectées, au vu de l'énoncé de l'issue.

*Oui j'ai fait cette issue mais je ne m'en souviens pas du tout*

**Comment by ascpial** [comment]
Il faudrait aussi ajouter l'affichage du type pour par exemple dans la commande `rolelink add`, afficher l'intérêt de `when` et les valeurs de `trigger`, ainsi qu'à tous les endroits où ce n'est pas indiqué correctement.
