### ISSUE TITLE
`Plugins/Wormhole` problems related to non-mapping of messages IDs

### ISSUE THREAD

**Issue by Aeris1One** [Curiosity-org/Gipsy#157]
Getting way more critical than we were thinking.

As we do not map messages through a database and only check similarities between messages when we edit them, there are false-positives and some problems may arise:
- when deleting a message, all similar messages in all linked channels get deleted (for example if you delete a message "Hello" all other "Hello" messages in the channel will get deleted)
- when editing a message, all similar messages sent by a webhook in all linked channels will get edited

As an example, if someone links a meme channel (were people only posts attachments without text) and you delete a message with only an attachment and an empty text, all similar messages will get deleted. 
I haven't tested as of now, but only messages sent by real people within 14 days would be deleted while all messages sent by a webhook would be if there's no restriction on webhook deleting its own messages.

We should consider mapping messages in database. Maybe we could purge mappings after 14 days because they would mostly be useless after this time.

**Comment by ascpial** [comment]
Tous les messages du salon cible ne seraient pas supprimés, seulement les quelques messages se situant dans le contexte du message qu'il faut modifier (à la même date).

Cependant, il est possible d'ajouter de nouvelles vérifications pour vérifier si les attachments correspondent (ce qui éviterait que des messages sans contenu texte mais avec des images soient supprimés en masse).

**Comment by ascpial** [comment]
Je vais retravailler un peu le plugin de wormhole pour essayer de régler les problèmes évoqués ici.
