### ISSUE TITLE
admin commands are not working

### ISSUE THREAD

**Issue by Damien0503** [Curiosity-org/Gipsy#201]
The bot does not react when using admin commands.

This is on my own bot instance, using pyenv and Python 3.10.10.

Custom prefix : _

Tested commands :
_admin pull
_admin activity play / watch / listen / stream
_admin reload
_admin shutdown
_admin branches
_admin reboot
_admin purge 5

The _help admin command works

And there is no error message in console.

I am admin of the bot in config.yaml file and I tested _config command which is working

**Comment by Damien0503** [comment]
To resolve this : remove the quotation marks from admin ID in config.yaml

**Comment by ascpial** [comment]
This should be assigned to configuration rewrite in #54.

**Comment by ZRunner** [comment]
Fixed in #211
